apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingupdate-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: rollingupdate-app
  template:
    metadata:
      labels:
        app: rollingupdate-app
    spec:
      containers:
      - name: rollingupdate-app
        image: nginx:alpine
        ports:
        - containerPort: 80
