apiVersion: v1
kind: Service
metadata:
  name: stable-service
spec:
  selector:
    app: stable-app
    version: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
