apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  labels:
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-app
      version: blue
  template:
    metadata:
      labels:
        app: blue-app
        version: blue
    spec:
      containers:
      - name: blue-app
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
