apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-app
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recreate-app
  template:
    metadata:
      labels:
        app: recreate-app
    spec:
      containers:
      - name: recreate-app
        image: ttl.sh/recreate-app-v1:1d #ttl.sh/recreate-app-v2:1d
        ports:
        - containerPort: 80
